const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, PageBreak, TableRow, TableCell, Table, WidthType, Header, Footer, PageNumber } = require("docx");

function heading(text, level = HeadingLevel.HEADING_1) {
  return new Paragraph({ heading: level, spacing: { before: 300, after: 200 }, children: [new TextRun({ text, bold: true, size: level === HeadingLevel.HEADING_1 ? 32 : level === HeadingLevel.HEADING_2 ? 28 : 24, font: "Times New Roman" })] });
}
function para(text, opts = {}) {
  return new Paragraph({ spacing: { after: 200, line: 360 }, alignment: AlignmentType.JUSTIFIED, children: [new TextRun({ text, size: 24, font: "Times New Roman", ...opts })] });
}
function bullet(text) {
  return new Paragraph({ spacing: { after: 120, line: 360 }, bullet: { level: 0 }, children: [new TextRun({ text, size: 24, font: "Times New Roman" })] });
}
function pageBreak() { return new Paragraph({ children: [new PageBreak()] }); }
function emptyLine() { return new Paragraph({ spacing: { after: 100 }, children: [] }); }
function centerPara(text, size = 24, bold = false) {
  return new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 }, children: [new TextRun({ text, size, font: "Times New Roman", bold })] });
}
function makeCell(text, opts = {}) {
  return new TableCell({ width: { size: opts.width || 4500, type: WidthType.DXA }, children: [new Paragraph({ children: [new TextRun({ text, size: 22, font: "Times New Roman", bold: opts.bold || false })] })] });
}
function makeTable(headers, rows) {
  const hRow = new TableRow({ children: headers.map(h => makeCell(h, { bold: true })) });
  const dRows = rows.map(r => new TableRow({ children: r.map(c => makeCell(c)) }));
  return new Table({ rows: [hRow, ...dRows], width: { size: 9000, type: WidthType.DXA } });
}

const ch1 = [
  heading("CHAPTER 1: INTRODUCTION"),

  heading("1.1 Background", HeadingLevel.HEADING_2),
  para("If you think about it, feedback is everywhere. When you order food from Swiggy, they ask you to rate the restaurant. When you finish an Uber ride, you rate the driver. When you download an app from the Play Store, you leave a review. Every business, every product, every service depends on feedback to get better. Without knowing what people think, you are basically flying blind. You might think your product is great, but if your users are struggling with a confusing button or a slow loading page, you will never know unless they tell you."),
  para("Now, here is the thing. Big companies have entire teams dedicated to collecting and managing feedback. They use tools like Jira, Zendesk, Canny, or UserVoice. These are powerful platforms that cost hundreds of dollars every month. They have ticketing systems, customer support workflows, priority queues, and detailed analytics dashboards. And they are absolutely worth the money if you are a company with thousands of customers and a team of product managers."),
  para("But what about the rest of us? What about a BCA student building a college project and wanting to know if their classmates find it useful? What about a freelancer who just launched a small website and wants to hear from their first ten users? What about a teacher who wants to collect feedback from students about a new course? These people do not need enterprise software. They do not have budgets. They just want a simple, clean tool where they can say hey, tell me what you think, and get actual useful responses back."),
  para("That is where the idea for FeedByMe came from. We looked around and realized that the existing tools fall into two buckets. The first bucket is free but basic. Google Forms is the obvious example. It works, it is free, and anyone can use it. But the moment you try to use it seriously, you hit walls. All responses go into a spreadsheet. There is no way to organize feedback by project. You cannot brand the form. There is no dashboard to see trends. If you want to know how many people reported bugs versus how many requested new features, you have to open Excel and make your own charts. That is not practical."),
  para("The second bucket is powerful but expensive. Tools like Canny start at four hundred dollars per month. Typeform gives you maybe ten responses for free and then asks you to pay. SurveyMonkey locks all the good features behind a paywall. These tools are designed for companies, not individuals. And even if you could afford them, they come with so many features that you spend more time configuring the tool than actually reading feedback."),
  para("So we decided to build something in the middle. Something that is free, looks professional, does not force users to create accounts, and gives you just enough features to actually manage feedback properly. That something is FeedByMe."),
  para("FeedByMe is a web-based multi-project feedback portal. The name says it all — feed me your thoughts. The core idea is dead simple. You sign up, create a feedback board for your project, get a link, and share it. Anyone who opens that link can rate your project on a scale of one to five stars, write their thoughts, attach a screenshot if needed, and hit submit. Their feedback appears on your board, and you can manage it from your dashboard. You can change its status, add a comment, filter by category, and see charts showing how your feedback breaks down by type and status."),
  para("We built FeedByMe using the MERN stack. MERN stands for MongoDB, Express.js, React.js, and Node.js. If you are not familiar with these, here is the short version. MongoDB is the database — it stores all the data. Express.js is the backend framework — it handles the server logic and API. React.js is the frontend library — it creates the user interface that people see and interact with. And Node.js is the runtime — it lets us run JavaScript on the server, not just in the browser. The nice thing about MERN is that you use JavaScript for everything. Frontend, backend, database queries, scripts — all JavaScript. It makes development smoother because you are not constantly switching between different languages and syntaxes."),

  heading("1.2 Objectives", HeadingLevel.HEADING_2),
  para("Before we started writing code, we made a list of what we wanted FeedByMe to do. This was important because it is easy to get carried away and start adding features that sound cool but nobody actually needs. We wanted to stay focused on solving the core problem — making feedback collection simple and organized. Here are the objectives we set for ourselves:"),
  bullet("Create a multi-project system where one user can manage feedback for several different projects from a single dashboard. For example, a developer working on three different apps should be able to create three separate boards and manage all of them from one account."),
  bullet("Generate a unique shareable link for every board. The link should be something anyone can open in their browser without needing to install anything or sign up for anything."),
  bullet("Allow guest submissions. This was a big one. Most feedback tools force people to create an account before they can say anything. We did not want that. If someone has an opinion, we want them to share it as quickly as possible. A guest should be able to submit feedback by just entering their email — no registration, no password, no hassle."),
  bullet("Include a five-star rating system so that feedback is not just text. A rating gives you a quick, quantifiable measure of satisfaction. You can look at your average rating and immediately know if people are generally happy or unhappy."),
  bullet("Let board owners add custom questions. Different projects need different information. A restaurant feedback form might ask about food quality and wait time. A software project might ask about which browser the user is on. We wanted board owners to be able to add their own questions beyond the default fields."),
  bullet("Support image uploads. Sometimes a screenshot says more than a paragraph of text. If someone finds a bug, they should be able to show you exactly what they see on their screen."),
  bullet("Build a proper authentication system with registration, login, logout, and a way to reset your password if you forget it."),
  bullet("Give board owners branding options. They should be able to pick a theme color and upload a logo so the board feels like it belongs to their project, not to FeedByMe."),
  bullet("Create an admin dashboard that shows analytics — total users, total feedback, average rating, charts showing feedback breakdown by status and category."),
  bullet("Make everything responsive so it works on phones, tablets, and desktops. In 2026, more than half of web traffic comes from mobile devices. If your tool does not work on a phone, you are losing half your audience."),
  bullet("Deploy the whole thing to the cloud so it can be accessed from anywhere, not just on localhost."),

  heading("1.3 Purpose", HeadingLevel.HEADING_2),
  para("The purpose of building FeedByMe is actually two things at the same time."),
  para("First, there is the practical purpose. We genuinely wanted to create something useful. As students, we have been in situations where we built a project and had no good way to collect feedback on it. We would share it with friends over WhatsApp, and they would send back messages like it is nice or it works. That is not helpful. We wanted to know what specifically works, what does not, and what they wish was different. FeedByMe gives us — and anyone like us — a structured way to ask those questions and get real answers."),
  para("Second, there is the academic purpose. This project is submitted as our final year BCA project. It is supposed to demonstrate that we have learned something over the past three years. And honestly, building FeedByMe touched almost every topic in the BCA curriculum. Database design? We designed four collections with relationships, indexes, and virtual properties. API development? We built a complete REST API with authentication, validation, file uploads, and error handling. Frontend development? We created sixteen pages with reusable components, context-based state management, and responsive CSS. Security? We implemented password hashing, JWT tokens, rate limiting, and input validation. Deployment? We configured the app for Vercel and MongoDB Atlas. If there is a better way to show what you have learned than building a working, deployed web application from scratch, we do not know what it is."),

  heading("1.4 Scope", HeadingLevel.HEADING_2),
  para("The scope of FeedByMe is broad but deliberately bounded. We wanted to build something complete enough to be genuinely useful, but not so complex that we would never finish it. Here is what falls inside the scope:"),
  para("User management is fully covered. People can register with their name, email, and password. They can log in, update their profile, and reset their password if they forget it. There are two roles — regular users and admins. Regular users can create boards and manage their own feedback. Admins can see everything — all users, all feedback, system-wide analytics."),
  para("Project management is fully covered. A user can create as many feedback boards as they want. Each board has a name, description, theme color, logo, and custom questions. Boards can be edited, deleted, and shared via a unique URL. When a board is deleted, all its feedback goes with it."),
  para("Feedback management is fully covered. Users and guests can submit feedback with a title, description, category, priority, star rating, tags, image attachment, and answers to custom questions. Feedback can be filtered by status, category, and priority. It can be sorted by date, rating, or upvotes. Board owners can update the status, add comments, and delete entries. Authenticated users can upvote feedback."),
  para("Admin features are covered. The admin dashboard shows total users, total feedback, average rating, and two charts. The admin can also view and manage user accounts."),
  para("What is NOT in scope: real-time updates via WebSockets, actual email delivery for password resets, payment processing, multi-language support, native mobile apps, and third-party API integrations. These are all things we would love to add eventually, but they were not realistic for the timeline of this project."),

  heading("1.5 Data Sources", HeadingLevel.HEADING_2),
  para("FeedByMe does not pull data from any external API or third-party service. All the data in the system comes from three sources, and all three are user actions within the application itself."),
  para("The first source is the registration form. When someone creates an account, they provide their name, email, and password. The name is stored as plain text. The email is stored in lowercase and validated against a regex pattern. The password is never stored as plain text — it goes through bcrypt hashing with twelve salt rounds before it touches the database. We also store a role field (user or admin) and timestamp fields for when the account was created and last updated."),
  para("The second source is the feedback submission form. This is where the bulk of the data comes from. A feedback submission includes a title (three to two hundred characters), a description (ten to five thousand characters), a category (picked from a dropdown with options like Bug, Feature Request, Improvement, General, and Other), a priority level (Low, Medium, High, or Critical), a star rating from one to five, optional tags, an optional image file, and answers to any custom questions the board owner set up. If the person is logged in, their user ID is stored as the author. If they are a guest, their email is stored instead."),
  para("The third source is the project creation form on the dashboard. When a user creates a new feedback board, they provide a project name, a description, a hex color code for the theme, an optional logo URL, and an array of custom question definitions. Each custom question has a label (the question text), a type (short text, long text, or star rating), and a flag indicating whether the question is required or optional."),
  para("All of this data is stored in MongoDB Atlas, which is a cloud-hosted database. We chose Atlas because it is free for small projects, it handles backups and security automatically, and it gives us a nice web interface to browse our data when we need to debug something."),

  heading("1.6 Problem Definition", HeadingLevel.HEADING_2),
  para("Let us put the problem in the simplest possible terms. Imagine you have just built a website for a client. You want to know what they think. What do you do? You could ask them on a call, but they will probably be polite and say it looks great even if it does not. You could send them a Google Form, but then you get responses in a spreadsheet with no context, no organization, and no way to track whether you have addressed each piece of feedback. You could set up a Trello board, but that requires them to learn Trello. You could try Canny, but that costs more than what the client is paying you for the website."),
  para("This is the core problem. There is no free, simple, dedicated tool for collecting organized, project-specific feedback with features like ratings, custom questions, image attachments, and guest access. Let us break down why each existing option falls short."),
  para("Google Forms is free, but it is generic. It was designed for surveys, not feedback. You cannot attach a feedback entry to a specific project. You cannot track its status (open, in progress, resolved). You cannot let users upvote each other's feedback. You cannot see charts showing how your feedback breaks down by type. And the form itself looks like a Google product, not your product. There is no branding."),
  para("Typeform looks beautiful, but the free tier is crippled. You get ten questions and ten responses per month. That is barely enough for a test run, let alone ongoing feedback collection. And even with a paid plan, Typeform is a form builder, not a feedback management system. There is no dashboard, no status tracking, no commenting."),
  para("Canny and UserVoice are the closest to what we need, but they are priced for companies with revenue. Four hundred dollars per month is simply not realistic for a student or a freelancer. These tools also come with a steep learning curve because they are designed for product teams, not individuals."),
  para("Then there is the login barrier. This is something most tools get wrong. They require users to create an account before submitting feedback. From a development standpoint, this makes things easier because you can track who said what. But from a user standpoint, it is a wall. People do not want to create yet another account. They do not want to verify their email. They do not want to remember another password. They just want to say hey, this button is broken and move on with their day. Research consistently shows that requiring registration drastically reduces response rates. FeedByMe solves this by letting guests submit with just their email — no account needed."),
  para("Finally, there is the customization gap. Most tools give you a fixed set of fields. But every project is different. A web app might need to know which browser the user is on. A delivery service might need to know the order number. A game might need to know the device model. FeedByMe lets board owners add their own custom questions with different field types, making each form tailored to its specific use case."),
  para("So to summarize the problem: there is no free tool that combines multi-project organization, guest access, custom questions, image uploads, star ratings, status tracking, and analytics in one clean package. FeedByMe is our answer to that problem."),
  pageBreak(),
];

module.exports = { ch1, heading, para, bullet, pageBreak, emptyLine, centerPara, makeTable, makeCell };
